### PR TITLE
in-137

### PR DESCRIPTION
**Pull request by Martianmellow12**
I added code to the `check_include` function in `compiler.py` that checks if the opcode is of type `input`. If it is, then it includes `stdio.h`, which is necessary since the `input` statement generates both a `printf` and `scanf` call.

### CODE REVIEW

**Review by frankhart2018 — APPROVED** [review]

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Doesn't work with the following code:-

```
MAIN
  var a = input()
END_MAIN
```

**Comment by Martianmellow12** [comment]
Is that valid syntax? It isn't in the documentation.

**Comment by frankhart2018** [comment]
Yeah it is valid, will add this in docs, thanks for pointing out. When you write ```input()``` it means that there is no prompt and the default type is string - "s".

**Comment by Martianmellow12** [comment]
Empty `input` calls caused gcc to throw warnings about empty `printf` statements, so I modified `compiler.py` to only generate `printf` calls when necessary. Note that there's a separate error where reading in strings doesn't work properly, however that's unrelated to this error, and I'll open an issue for that one separately.

**Comment by frankhart2018** [comment]
Hey @Martianmellow12 it still does not include stdio.h with this code:-

```
MAIN
	var a = input()
END_MAIN
```

**Review by frankhart2018 — APPROVED** [review]

**Comment by frankhart2018** [comment]
Looks good, thank you for your contribution @Martianmellow12. Closes #137.

**Pull request merged**
