### PR TITLE
Added functionality for Array indexing on LHS

### PR DESCRIPTION
**Pull request by PranshulDobriyal**

### CODE REVIEW

**Comment by Math-O5** [comment]
@PranshulDobriyal I was doing it too... But I preferred your version. May I update some few details that is missing?

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
1) I feel that there should be an error message for when there is no index, e.g arr[], this should not be allowed.
2) Also when the index is not of type integer you need to throw:- Expected integer index for array, not Expected integer size of array.
3) Can you move the lines 341-343 to somewhere before 340, it is looking like that is part of the check if assignment operator follows identifier name.
4) Please use a descriptive variable name instead of j (introduced in line 341).
5) Update arr_surplus to something like arr_idx_val, arr_surplus doesn't tell much about what it contains. 
6) The branch name is not in correct format.

**Comment by frankhart2018** [comment]
> @PranshulDobriyal I was doing it too... But I preferred your version. May I update some few details that is missing?

Can you mention the details that are missing here?

**Comment by PranshulDobriyal** [comment]
@Math-O5 Currently there is no support for expressions inside the brackets i.e
var a[size+1] 
a[b+5] = 10
Will both throw errors

**Comment by Math-O5** [comment]
@frankhart2018 This version is allowing access out of index too.

**Comment by Math-O5** [comment]
@PranshulDobriyal Tnxs for remember. Should just reopen PR or you prefer change the name branch then I merge with mine?

**Comment by Math-O5** [comment]
@frankhart2018 Check if expression is inside range can be fully done in compilation time, because of definition of variable. So we should try predicted when possible or let it free checks?

**Pull request closed without merging**
