### PR TITLE
Added a feature (question number114)

### PR DESCRIPTION
**Pull request by Erzmafia**
made the changes you asked for .

### CODE REVIEW

**Comment by Erzmafia** [comment]
this PR is part of SWOC

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
1) Can you use PI (https://cimplec.github.io/docs/doc.html#mathcons) instead of hardcoded constant?

**Comment by Erzmafia** [comment]
i have used PI function and modified answer little bit .

**Review by Math-O5 — APPROVED** [review]

**Comment by Math-O5** [comment]
@Erzmafia The vol2 is giving zero is it not? I think 0.00015^3 is to slow number. I think the number is wrong, why do you is dividing by 1.5cm by 1000? 100cm is 1m, so is (1.5/100)m or pass the greater ball to centimetre(cm), which will give you 3m - 300cm

**Review by Math-O5 — CHANGES_REQUESTED** [review]
Adjust unit used. Make sure the answer is right.

**Review by frankhart2018 — APPROVED** [review]

**Pull request merged**
