### PR TITLE
In 361 - check_if always overflow.

### LINKED ISSUE #361: [BUG REPORT] Throwing simc overflow error to user
**Describe the bug**
When user type incomplete programs, the "check_if[i + 1]" will always overflow. 

The sintax is wrong, but the program should treat this properly. 

**To Reproduce**
Complie this simc code:

test.simc:

```
MAIN
    if()
```

```
MAIN
    var
```

```
MAIN
    f
```

```
MAIN
    array overflow
```

**Expected behavior**
A kind message error for user

**Desktop (please complete the following information):**
 - OS: Fedora 30, Ubuntu 18

### PR DESCRIPTION
**Pull request by jigyasudhingra**
Fixed #361 bug.
Created another function name check_incomplete in global_helpers.py.

It passes the test for given code:
```
MAIN
    if( )
```
```
MAIN
    while()
```
```
MAIN
    switch()
```
```
var
```
```
f
```

I thought of putting the **check_incomplete** code inside the **check_if**, but for that I have to put two more arguments in check_if and then pass those arguments in every check_if calls.

Another reason, we have to call check_incomplete just before **the checking of newline code or before left_brace checking**, so it becomes very difficult to bypass other check_if calls, which are encounter before that. Otherwise, it will going to throw overflow error due to **while_loop** which becomes **infinite** for checking newline.

### CODE REVIEW

**Comment by Math-O5** [comment]
@jigyasudhingra ok, then. Well done.

**Review by Math-O5 — CHANGES_REQUESTED** [review]
@jigyasudhingra Still getting error...

Pieces like this bellow may overflow: 

```
 while tokens[i].type == "newline":
                i += 1
```
The solution is have a function as:

```
while token_is_equal(tokens, i, "newline"):
       i += 1

if token_is_equal(tokens, i + 4, "braces"):
   // safe executed
```

For the check_if, it always compare tokens, then you can change it to:

```
def check_if(tokens, i, expected, msg, line_num):
     ....
```

**Comment by Math-O5** [comment]
@jigyasudhingra If you need a pull request approved today for an event as KwoC2020, I recommend check the issue #417 before continue this.

**Comment by jigyasudhingra** [comment]
> @jigyasudhingra Still getting error...
> 
> Pieces like this bellow may overflow: 
> 
> ```
>  while tokens[i].type == "newline":
>                 i += 1
> ```
> The solution is have a function as:
> 
> ```
> while token_is_equal(tokens, i, "newline"):
>        i += 1
> 
> if token_is_equal(tokens, i + 4, "braces"):
>    // safe executed
> ```
> 
> For the check_if, it always compare tokens, then you can change it to:
> 
> ```
> def check_if(tokens, i, expected, msg, line_num):
>      ....
> ```

Okaty, I will try.

Can you tell which case still gets you an error.

**Comment by Math-O5** [comment]
@jigyasudhingra When the SimC end with newlines,

Simc:
```
MAIN 
     if()'\n
\n
\n
\n
```

**Comment by jigyasudhingra** [comment]
@Math-O5 
On removing this:
```
if tokens[i + 1].type == "newline":
        i += 1
        while tokens[i].type == "newline":
            i += 1
        i -= 1
```
Then the issue is resolved but the error is not suitable which is coming up.
```
[Line 3] Error: No matching END_MAIN for MAIN
```
So, I have to change the error which is coming up or is it ok?

**Comment by jigyasudhingra** [comment]
Hey @Math-O5, 
Resolved only **if_statement** for now.

I removed this:
```
if tokens[i + 1].type == "newline":
        i += 1
        while tokens[i].type == "newline":
            i += 1
        i -= 1
```
then, **newline** problem is resolved.

**Pull request closed without merging**
