### PR TITLE
Added q102.simc

### PR DESCRIPTION
**Pull request by rahulhambarde300**

### CODE REVIEW

**Comment by rahulhambarde300** [comment]
#307

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
The output isn't correct, please check your code before submitting a PR.

**Comment by rahulhambarde300** [comment]
I've added the comment after the code ran. 
So, I think the compiler has a bug. 
It doesn't properly analyse a comment. 
If you use integers without any string or the variables from your code in a line, you'll get error. 
So,I've changed my code, removed the variable names from comment and uploaded.

**Comment by rahulhambarde300** [comment]
Hello @frankhart2018 I've changed my code. Please do check it.

**Review by frankhart2018 — APPROVED** [review]
Looks good, thank you for your contribution @rahulhambarde300. Closes #307. Also the bug that you are referring to has been fixed, thanks for reporting it though :).

**Pull request merged**
