### PR TITLE
Symbol Table looks more presentable. Used magic functions

### LINKED ISSUE #478: [FEATURE] Pretty print symbol table
**Describe the feature and the solution**
Currently if we print the symbol table it prints the dictionary, it would be easier if it was displayed as proper table format. This functionality can be added by adding a __str__ magic method to symbol table class.

### PR DESCRIPTION
**Pull request by Chasmiccoder**
This Pull Request is part of SWoC 2021.
Closes #478

**Implementation details**
Used Magic Function _ _ str _ _( ) to print the Symbol Table in an organised manner

**simC Code**
MAIN
    print( "Hello World\n" )
    var a = input( "Enter integer: ", "i" )
    a = a * 2
    print( "Double of integer: {a}" )

END_MAIN

image

Number of Unit Tests Passing: 273
image

Number of Code Tests Passing: 106
image

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Add the number of unit and code tests passing, it was in the PR format, please don't delete stuff from PR template, they are not optional (unless mentioned)

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Also check the table for this code, for me this leaks the right boundary:-

```python
struct Student {
	var rollno
	var name
}

MAIN
	Student s
	s.rollno = 1
	s.name = "Siddhartha"
	
	print(s.rollno)
	print(s.name)
END_MAIN
```

This gives:-

Screenshot 2021-01-26 at 5 41 22 PM

**Comment by Chasmiccoder** [comment]
@frankhart2018 
Sorry, I will keep that in mind.
Yes, I'll work fixing this now

**Comment by Chasmiccoder** [comment]
Update:
Simc Code:
struct Student {
	var rollno
	var name
    var n1
    var n2
    var n3
}
struct employee {
    var a1
    var b1
}

MAIN
	Student s
	s.rollno = 1
	s.name = "Siddhartha"
	
	print(s.rollno)
	print(s.name)

END_MAIN

Output:
image

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this. Thanks for contributing @Chasmiccoder. Closes #478.

**Comment by Chasmiccoder** [comment]
Thanks!

**Pull request merged**
