### PR TITLE
In 356 & 357 - Added support for structure declaration and instantiation in the definition

### PR DESCRIPTION
**Pull request by 10Kaiser10**
#356 and #357

### CODE REVIEW

**Review by Math-O5 — CHANGES_REQUESTED** [review]
@10Kaiser10 Thank you by the contribution. I'm careful testing your code, but to be merged, it must follow the CONTRIBUTING.md instructions. For your case, you can created two branch,each named of **in-356** and **in-357**. But you can submit in one branch too -> named **in-356-357**. Note: you can have two merges instead of one, although it is your decision.

**Comment by 10Kaiser10** [comment]
I am sorry, please explain this again. Do I need to create a branch in my forked repo named in-356-357 and then make the pull request?

**Comment by Math-O5** [comment]
@10Kaiser10 Yes, that's it

**Comment by Math-O5** [comment]
@10Kaiser10 But you can create two branchs too! 'in-356' and 'in-357' and split the code, but no need for that.

**Review by Math-O5 — APPROVED** [review]

**Comment by Math-O5** [comment]
@10Kaiser10  Well done!

**Pull request merged**
