### PR TITLE
In 433

### PR DESCRIPTION
**Pull request by Chasmiccoder**
_**This PR is part of SWoC 2021**_

Fixed Issue #433
Now, array_parser uses the expression( ) function from simc_parser to parse array initializers. 

Also, added a new feature in simc_parser's expression( ) function. It takes an argument 'block_type_promotion', which can be set to True, in order to prevent block type promotion during parsing.

### CODE REVIEW

**Review by frankhart2018 — COMMENTED** [review]
1) The error message for when the number of tokens parsed don't match should be something like - Expected 4 entries got 2 entry, given the code was:- var arr[4] = {1, 2}. Array not parsed correctly isn't a very clear message, as a user I would have no idea what went wrong.
2) I don't understand the logic of this if-elif-else in line 105-111, can you add some comments there?

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Update with above mentioned changes

**Comment by Chasmiccoder** [comment]
Hi there @frankhart2018 
I added the comment lines, and also changed the way the errors are handled.
Hope it's fine now.

**Comment by Chasmiccoder** [comment]
I have made that section of the code more comprehensive
Hope it's fine now :)

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this. Thanks for contributing @Chasmiccoder. Closes #433.

**Comment by Chasmiccoder** [comment]
> Looks good, merging this. Thanks for contributing @Chasmiccoder. Closes #433.

yay!

**Pull request merged**
