### PR TITLE
Added support for single line stats for if/else and loops

### PR DESCRIPTION
**Pull request by shobhit10058**
concerns issue #27 
Changes with code are given here -
https://github.com/cimplec/sim-c/issues/27#issuecomment-743956251
This will add support for single-line statements for if/else and loops.

### CODE REVIEW

**Comment by shobhit10058** [comment]
can someone verify?

**Comment by shobhit10058** [comment]
can someone test this?

**Review by Math-O5 — CHANGES_REQUESTED** [review]
@shobhit10058 Only on next week I will test all code and add up what's missing e.g (cascade if/else). For functions definition, C does not accept without braces, but we can accept it in SimC and then add the braces in  C code final. What you can do is required only one newline of code valid.

Accepted functions case examples: 

```
fun sum return (a + b)

fun sum
      return a + b

fun sum print ( map(a + b) )

fun sum
      return map(a + b)
```


 uy m

**Comment by shobhit10058** [comment]
So, I have to add support for single line functions also. Okay,Then I will try and update the PR.

**Comment by shobhit10058** [comment]
@Math-O5 ok, Then I am assuming that the single statement will be written in a single line which I think is necessary for many other functioning also.

**Comment by frankhart2018** [comment]
@shobhit10058 No not necessarily, if the user want he/she can put this in separate line, while parsing you can check for \n and just increment line_num and skip them.

**Comment by shobhit10058** [comment]
after the changes the improvements can parse the following simc code -
```
fun sum(a,b)


	return a + b

fun sum1(a,b)


	return a + b
}

fun sum2(a,b)


	return a + b

	
fun check_for()

	for i in 3 to 7 by + 2
		print(2*i)
		
fun check_print()
	
	print(3)
	
fun check_ret()
	
	return 3
	
fun check_do_while(i)
	do
	i *= 2
		print(i ++)
	while(i < 3)	

fun check_while(i)
	while(i < 10)
		print(i++)
	
MAIN
	var i = 0
	while(i < 10)
		print(i ++)
	if(i > 1)
		print(i)
	else
		print(1)
	for i in    1 to 6 by +2 
		print(i)
	do
		print(i)
		i++;
	while(i<20)
	var c = sum(1,2)
	sum1(1,2)
	sum2(1,2)
	check_do_while(1)
	check_while(2)
END_MAIN
```
as -
```
#include <stdio.h>

int sum(int a, int b) {

	return a + b;
}

int sum1(int a, int b) {

	return a + b;
}

int sum2(int a, int b) {

	return a + b;
}

void check_for(void) {
	for(int i = 3; i < 7; i+=2) 	printf("%d", 2 * i);
}

void check_print(void) {
	printf("%d", 3);
}

int check_ret(void) {

	return 3;
}

void check_do_while(int i) {
	do {
	i *= 2;
	printf("%d", i ++ );
}
	while(i < 3);}

void check_while(int i) {
	while(i < 10) 	printf("%d", i ++ );
}

int main() {
	int i = 0;
	while(i < 10) 	printf("%d", i ++ );
	if(i > 1) 	printf("%d", i);
	else 	printf("%d", 1);
	for(int i = 1; i < 6; i+=2) 	printf("%d", i);
	do {
	printf("%d", i);
	i++;
	}
	while(i < 20);	int c = sum(1, 2);
	sum1(1, 2);
	sum2(1, 2);
	check_do_while(1);
	check_while(2);

	return 0;
}
```

**Comment by shobhit10058** [comment]
@Math-O5 can you verify it once?

**Comment by Math-O5** [comment]
@shobhit10058  Seems good, now all is missing is rename branch to **`in-27`** and If you write simc code it compile 

```
fun name()

MAIN
END_MAIN
```

to C code:

```
void name() {

void main() {

}
```
The code above should close the braces.

**Comment by shobhit10058** [comment]
fixed -
simc code -
```

fun sum1(a, b)

	return a + b

fun empty()



fun sum()


MAIN
sum1(1, 2)

END_MAIN
```

c code -
```


int sum1(int a, int b) {

	return a + b;
}

void empty(void) {
}

void sum(void) {
}

int main() {
	sum1(1, 2);

	return 0;
}
```

**Comment by Math-O5** [comment]
@shobhit10058 Fast!

**Comment by shobhit10058** [comment]
I think I would need to create a pull request if I renamed this branch

**Comment by Math-O5** [comment]
@shobhit10058 I'm really grateful by the work. Tomorrow I will look the code. Remember rename the branch (in-27)!

**Comment by Math-O5** [comment]
@shobhit10058 you can do it, actually, the PR will close automatic.

**Pull request closed without merging**
