### PR TITLE
Support for single stats if/else, loops and functions

### PR DESCRIPTION
**Pull request by shobhit10058**
concerns issue #27 
The changes are highlighted here https://github.com/cimplec/sim-c/pull/404 . This contains the same code as that branch just the name is changed.

### CODE REVIEW

**Comment by Math-O5** [comment]
@shobhit10058 Tests passed. @frankhart2018 What you think of the code?

**Comment by Math-O5** [comment]
@shobhit10058 It's a bit complex understand what you did. This variable  `func_st` and it's comments is not very clear what is happing. May you think in another name? Like `funct_scope`, and instead sum `+=` on it, would be nice if you declare some constant as bellow:

```
    # Function not called
    NO_FUNC_CALLED = -1

    # Function start body
    START_FUNCTION = 0

    # Function end body 
    END_FUNCTION = 1 
```

Now, one suggestion of comment of `func_st` is  `Flag which mark scope of functions without braces`.

**Comment by shobhit10058** [comment]
So, I have to change the name of func_st. I thought It as a flag for a start of function with a single statement i.e one who's body  is used without the braces.

**Comment by shobhit10058** [comment]
Ok, I understood what you are saying. I will update the PR. 
So, I have to change the name of the flag
I have to give names to the constants -1,0 and 1.

**Comment by shobhit10058** [comment]
now the unmatched braces one is not working it will give error.  Rest all are working.

**Review by Math-O5 — APPROVED** [review]
@shobhit10058 Well done!

**Review by Math-O5 — APPROVED** [review]
@shobhit10058 Well done!

**Pull request merged**
