### PR TITLE
Added support for Bitwise operations

### PR DESCRIPTION
**Pull request by shobhit10058**
concerns issue #32.
I have added the following feature:
Simc can now support bitwise operations and, xor, or.
The bitwise add operation is used as a & b and a&= b now.
The bitwise or operation is used as a | b and a |= b now.
The bitwise xor operation is used as a ^ b and a ^= b now.
Since the power was previously using the ^ operator, it needed to be redefined.
Now the power is available as a ** b.
Following is the test case -
```
MAIN
	var a = 10
	print(10&   a)
	var b = 5
	b ^= a
	a |= b
	a &= b
	print(b   &a)
	print( 10  ^ a)
	print (a |    b)
END_MAIN
```
Converted to -
```
#include <stdio.h>

int main() {
	int a = 10;
	printf("%d", 10 & a);
	int b = 5;
	b ^= a;
	a |= b;
	a &= b;
	printf("%d", b & a);
	printf("%d", 10 ^ a);
	printf("%d", a | b);

	return 0;
}
```
Generated tokens -
```
Token('MAIN', '', '1')
Token('newline', '', '1')
Token('var', '', '2')
Token('id', '1', '2')
Token('assignment', '', '2')
Token('number', '2', '2')
Token('newline', '', '2')
Token('print', '', '3')
Token('left_paren', '', '3')
Token('number', '3', '3')
Token('bitwise_and', '', '3')
Token('id', '1', '3')
Token('right_paren', '', '3')
Token('call_end', '', '3')
Token('newline', '', '3')
Token('var', '', '4')
Token('id', '4', '4')
Token('assignment', '', '4')
Token('number', '5', '4')
Token('newline', '', '4')
Token('id', '4', '5')
Token('bitwise_xor_equal', '', '5')
Token('id', '1', '5')
Token('newline', '', '5')
Token('id', '1', '6')
Token('bitwise_or_equal', '', '6')
Token('id', '4', '6')
Token('newline', '', '6')
Token('id', '1', '7')
Token('bitwise_and_equal', '', '7')
Token('id', '4', '7')
Token('newline', '', '7')
Token('print', '', '8')
Token('left_paren', '', '8')
Token('id', '4', '8')
Token('bitwise_and', '', '8')
Token('id', '1', '8')
Token('right_paren', '', '8')
Token('call_end', '', '8')
Token('newline', '', '8')
Token('print', '', '9')
Token('left_paren', '', '9')
Token('number', '6', '9')
Token('bitwise_xor', '', '9')
Token('id', '1', '9')
Token('right_paren', '', '9')
Token('call_end', '', '9')
Token('newline', '', '9')
Token('print', '', '10')
Token('left_paren', '', '10')
Token('id', '1', '10')
Token('bitwise_or', '', '10')
Token('id', '4', '10')
Token('right_paren', '', '10')
Token('call_end', '', '10')
Token('newline', '', '10')
Token('END_MAIN', '', '11')
Token('newline', '', '11')
```

### CODE REVIEW

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this. Thanks for your contribution. Closes #32.

**Comment by Math-O5** [comment]
@frankhart2018 I think it passed a variable in Camelcase, is it a problem?

**Comment by Math-O5** [comment]
@frankhart2018 I just run this test: 

```
MAIN
    var i = 2
    var j = i || 15
    var z = i^j
    var g = i**j
    
END_MAIN
```

And code generated was:

```
#include <math.h>

int main() {
	int i = 2;
	int j = i || 15;
	int z = pow(i, j);
	int g = i *  * j;

	return 0;
}
```

**Comment by frankhart2018** [comment]
Did you run it using the recent build, I merged it some time back, make sure you reinstall @Math-O5

**Comment by frankhart2018** [comment]
Yeah true @Math-O5, I completely forgot about the camel case. Will make the change.

**Comment by Math-O5** [comment]
@frankhart2018 Ops, I didn't see it update!

**Pull request merged**
