### PR TITLE
[in-166] Added code for Q58, Finding Avg of 7 num

### PR DESCRIPTION
**Pull request by DevLokCodes**
_Finding the Average of 7 numbers when average of 6 numbers and 7th number is given._

### CODE REVIEW

**Review by dhairyaj — COMMENTED** [review]
@DevLokCodes , please check the issue number and then make the correct branch. This is not the issue number for the problem that you have submitted.

**Comment by DevLokCodes** [comment]
i believe the issue number given to the problem was Q58 
image

**Review by DevLokCodes — COMMENTED** [review]
Corrected the Issue number, my bad

**Comment by frankhart2018** [comment]
Where have you corrected?

**Pull request closed without merging**
