### PR TITLE
Created q96.simc : Convert Kgs to pounds

### PR DESCRIPTION
**Pull request by rahulhambarde300**

### CODE REVIEW

**Comment by rahulhambarde300** [comment]
#301

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
The file extension is incorrect.

**Comment by rahulhambarde300** [comment]
I'm sorry,  I pasted my code and made a mistake..
I'll solve it.

**Review by frankhart2018 — APPROVED** [review]
Looks good, thank you for your contribution @rahulhambarde300. Closes #301.

**Pull request merged**
