### PR TITLE
Fixing incorrect error message

### LINKED ISSUE #437: [BUG REPORT] Incorrect error message when function is not defined
**Describe the bug**
When a function is not defined but is called the error message should be like:- "Function <func-name> is not defined", but it throws an error regarding the mismatch of number of formal and actual params. 

**sim-C Code**
```
MAIN
    sum(1, 2)
END_MAIN
```

**Error Message**

[Line 2] Error: Expected not more than 0 arguments but got 2 in function sum

### PR DESCRIPTION
**Pull request by sayandip18**
Taken over from #450. Fixes #437. This PR is part of SWoC 2021.

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
It still has the same error message.

**Comment by sayandip18** [comment]
> It still has the same error message.

I just pushed the changes. I'll merge these commits into one since both are quite small and the commit message needs to be rectified.

**Comment by frankhart2018** [comment]
@sayandip18 Are the changes made? Otherwise I will close this PR.

**Comment by frankhart2018** [comment]
Stale PR closing this.

**Pull request closed without merging**
