### PR TITLE
Added simC code for question 33 #78

### PR DESCRIPTION
**Pull request by Priyanshu-official**
Added simC code for question 33 #78 
Compute the value of the following series till the nth term.

### CODE REVIEW

**Comment by frankhart2018** [comment]
Hey @Priyanshu-official can you do this without the Raw C injection.

**Comment by Priyanshu-official** [comment]
@frankhart2018 
ya sure Let me try
and in Pls check Conversation
Pervious one When I ask for help in Raw C

**Comment by Priyanshu-official** [comment]
@frankhart2018 Pls Review now it's Without Raw C

**Comment by frankhart2018** [comment]
One small change, branch name is not proper.

**Comment by Priyanshu-official** [comment]
ya I was also Forget I created a branch on 30sept

**Comment by frankhart2018** [comment]
Please change the branch name. Thanks.

**Comment by Priyanshu-official** [comment]
@frankhart2018  Branch Name Should be Q33 ? right

**Comment by frankhart2018** [comment]
Or leave, I can consider this one.

**Comment by frankhart2018** [comment]
Merging this

**Comment by Priyanshu-official** [comment]
Thank you

**Pull request merged**
