### PR TITLE
BugFix : Make sure return statements are inside functions

### LINKED ISSUE #257: [BUG REPORT] return statement outside function definition
**Describe the bug**
Simc allows for return function to be outside function definition scope

**To Reproduce**
simc code:
```bash
fun a(){

	print("hello world")
}
return 1
MAIN
	a()
END_MAIN
```
c code generated:
```bash
 #include <stdio.h>

int a(void) {
	printf("hello world");
}

	return 1;

int main() {
	a();

	return 0;
}
```
**Expected behavior**
 should give error stating return function used outside function definition

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux

### PR DESCRIPTION
**Pull request by YJDoc2**
Fixes #257
Now any return statements outside functions generate error.
Also return statements inside main functions are supported now.

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Hey @YJDoc2 the return statement for functions looks good, but for custom return in main function you will have to make changes in the compiler too as it still generates return 0 (two return statements are generated in compiled C code). Though it doesn't matter as the second return statement won't be reached but it is kind of unnecessary to have two return statements.

**Comment by YJDoc2** [comment]
I think it's a good redundancy, as if someone forgets to add a return , say in one of the branches of if-else or something, we will still have an ending return. And as you said , it won't be reached otherwise, and C compiler will simply remove it from generated binary as unreachable code.
Or we can remove the default return statement completely, as no return in int main is considered as return 0, at least in gcc.
Which way would be preferable?

**Comment by frankhart2018** [comment]
I think the best way will be to have a flag inside the compiler that checks whether a return statement is inside main function or not, and if it is there then we don't compile the return 0; statement if on the other hand this flag is off when the compiler reaches END_MAIN opcode then compile the old return 0; statement before the END_MAIN. That way there won't be any redundant return statements.

**Comment by YJDoc2** [comment]
made the requested changes
Now the default return is put only if no return is provided.

**Review by frankhart2018 — APPROVED** [review]
Looks good, thank you for your contribution @YJDoc2. Closes #257.

**Pull request merged**
