### PR TITLE
Added simc-code for Q39

### PR DESCRIPTION
**Pull request by Priyanshu-official**
#84 
Added Code in 
simc-code/q39.simc

### CODE REVIEW

**Comment by Priyanshu-official** [comment]
@frankhart2018 please Review This

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
1) Remove the compiled C file.
2) Put your code inside MAIN and END_MAIN not inside code blocks ( { } )

**Review by Priyanshu-official — COMMENTED** [review]
review changes

**Review by frankhart2018 — APPROVED** [review]
Looks good, thank you for your contribution @Priyanshu-official.

**Pull request merged**
