### PR TITLE
Change lexical analyzer to identify 'or' and 'and' tokens

### LINKED ISSUE #189: [BUG REPORT] OR (||) is not translated correctly
**Describe the bug**
Or symbol || was not translated. Here is an example from solving issue #161 

```
MAIN
    // Compute the area of a rhombus, given its bases
    // The bases are float inputs

    // Get the two bases
    var p = input("First basis : ", "f")
    var q = input("Second basis : ", "f")

    // Verify that the bases are positive
    if(p<0 || q<0) {
        print("Bases cannot be negative")
    } else {
        var area = p*q/2

        print("Area of the rhombus ({p}, {q}) is {area}")
    }
END_MAIN
```
and the c-code
```

#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	//  Verify that the bases are positive 
	if(p < 0q < 0) {
	printf("Bases cannot be negative");
	}
	else {
	float area = p * q / 2;
	printf("Area of the rhombus (%f, %f) is %f", p, q, area);
	}

	return 0;
}
```

**To Reproduce**
1. Install simc as stated in documentation  `pip install git+https://github.com/cimplec/sim-c`
2. Translate the code given above

**Expected behavior**
The following code should be generated 
```

#include <stdio.h>

int main() {
	//  Compute the area of a rhombus, given its bases 
	//  The bases are float inputs 
	//  Get the two bases 
	float p;
	printf("First basis : ");
	scanf("%f", &p);
	float q;
	printf("Second basis : ");
	scanf("%f", &q);
	//  Verify that the bases are positive 
	if(p < 0 || q < 0) {
	printf("Bases cannot be negative");
	}
	else {
	float area = p * q / 2;
	printf("Area of the rhombus (%f, %f) is %f", p, q, area);
	}

	return 0;
}
```

**Desktop (please complete the following information):**
 - OS: Arch, with Kernel 5.8.12, using python 3.8.5 and pip 20.1.1

I can try to investigate and fix the error.

### PR DESCRIPTION
**Pull request by nanoy42**
Changed lexical analyser to correctly identify 'and' and 'or' tokens.

The double-symbols `&&` and `||` are assimilated to one token ('and' and 'or' respectively) and the line
```
if (p >= 0 || q >= 0) {
```

now gives

```
Token('if', '', '10')
Token('left_paren', '', '10')
Token('id', '1', '10')
Token('greater_than_equal', '', '10')
Token('number', '7', '10')
Token('or', '', '10')
Token('id', '4', '10')
Token('greater_than_equal', '', '10')
Token('number', '8', '10')
Token('right_paren', '', '10')
Token('call_end', '', '10')
Token('left_brace', '', '10')
```
The identification of the symbol "&" was also changed in order to differentiate between an "and" token and an "address_of" token.
Fixes #189

### CODE REVIEW

**Review by frankhart2018 — COMMENTED** [review]
1) Incrementing i only by 1 in AND and OR makes the lexical analysis loop check the second character of && and || too which I don't think is necessary.

**Comment by nanoy42** [comment]
Yep that's true. I removed unnecessary conditions and updated the PR

**Comment by frankhart2018** [comment]
No no I was talking about the i+=1, when scanning through && it will scan both of them in two separate passed through the loop. If on the other hand you update i+=2 when && appears then both &s are scanned in the same pass.

**Comment by nanoy42** [comment]
Ok I misunderstood. I think that's good now (also that simplified the code)

**Review by frankhart2018 — APPROVED** [review]
Looks good, thank you for your contribution @nanoy42. Closes #189.

**Pull request merged**
