### PR TITLE
In-25 Add dependency of variable 

### LINKED ISSUE #25: [BUG REPORT] Cannot infer type of parameter in function
**Describe the bug**
Cannot infer type of parameter inside function body. The type inference here should be done after calling but is being done in the definition itself.

**To Reproduce**
<ins>simC code</ins>:-
```c
fun sum(a, b) {
  var c = a+b
  return c
}

MAIN
var d = sum(1,2)
END_MAIN
```

<ins>C Code</ins>:-
Not generated, throws error.

**Expected behavior**
<ins>C Code</ins>:-
```c
int sum(int a, int b) {
  int c = a+b;
  return c;
}

int main() {
  int d = sum(1,2)

  return 0;
}
```

### PR DESCRIPTION
**Pull request by Math-O5**
Closes #25

**OBS**
1. If this kind solution is approved, I'll improve comments and resolve conflicts. 

2. Should the functions add_dependency and resolve_dependency be located at variable parser or symbol_table? (Current at variable_parser). 

**Implementation details**
Added the field of variable dependency in SymbolTable. So when a variable is typed after assignment, it can wait for the definition. When a variable is not defined, it'll remain "declared" and for now is not throwing error.  

Symbol Table:
[id, name_var, type, metatype, **WHO_DEPENDES_OF_ME_ID_LIST**]

 **WHO_DEPENDE_OF_ME_ID_LIST = 'id-id-id-id'**

**Test Case 1**

**simC Code**
```
fun sum(a, b) {
	var k = a + b
}
```

```
MAIN
	var c
	var e
	var d = c + e

	c = 3

	sum(1, 2)	
END_MAIN
```

**C Code (If generated)**

```
void sum(int a, int b) {
	int k = a + b;
}

int main() {
	int c;
	declared e;
	int d = c + e;
	c = 3;
	sum(1, 2);

	return 0;
}
```

**Test Case 2**

**simC Code**
```
fun sum(a, b) {
	var k = a + b
        return k
}
```

```
MAIN
	var c
	var e
	var d = c + e

	c = 3

	sum(1, 2)	
END_MAIN
```

**C Code (If generated)**

```
int sum(int a, int b) {
	int k = a + b;

       return k;
}

int main() {
	int c;
	declared e;
	int d = c + e;
	c = 3;
	sum(1, 2);

	return 0;
}
```
**Error message (If any)**
_"Cannot assign more than one type for variable"_ // When more than one type is assigned

Number of unit tests passing: 2/2
Number of code tests passing:  106/106

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Hey @Math-O5 I think the code for #359 is also here, can you remove those, it is easier if they are in separate PRs.

**Comment by Math-O5** [comment]
@frankhart2018 Done. Any other changes now are related from in-25.

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
1) Line 680 in simc_parser, update it to not type_.startswith(“struct_var”)
2) I think we should not block the assigning in resolve_dependency, rather a type promotion seems to be a better option to me. So, if the child_type is smaller in precedence to type_ then assign otherwise throw error that cannot downgrade the type or something.
3) Also as you mentioned these two functions (add and resolve dependency) makes more sense in symbol table and not in variable parser.

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Also I don't think you changed compiler to account for the fourth entry in symbol table. Due to this many code tests are failing. Please use the test-suite to test your code before submitting a PR.

**Comment by Math-O5** [comment]
@frankhart2018 I think I stashed the changes... I had to do again, almost finishing

**Comment by Math-O5** [comment]
@frankhart2018 Done

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
I don't think you ran the tests yet, because if you had run the tests you would have realized in how many places you have missed accounting for the dependency field in symbol table. Please run the unit tests before submitting.

**Comment by Math-O5** [comment]
@frankhart2018 Yep, it was missing! But all test units passed here. I think is because there is not so many code using struct and arrays; then the code does not pass be there.

**Review by frankhart2018 — COMMENTED** [review]
1) I think you are confusing codetests with unittests, many unittests are failing.
2) Please remove the test directory, we migrated to separate test suite

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this. Closes #25.

**Pull request merged**
