### PR TITLE
[BUG] check_if always overflow

### LINKED ISSUE #361: [BUG REPORT] Throwing simc overflow error to user
**Describe the bug**
When user type incomplete programs, the "check_if[i + 1]" will always overflow. 

The sintax is wrong, but the program should treat this properly. 

**To Reproduce**
Complie this simc code:

test.simc:

```
MAIN
    if()
```

```
MAIN
    var
```

```
MAIN
    f
```

```
MAIN
    array overflow
```

**Expected behavior**
A kind message error for user

**Desktop (please complete the following information):**
 - OS: Fedora 30, Ubuntu 18

### PR DESCRIPTION
**Pull request by jigyasudhingra**
Trying to fix #361 bug, and it is fixed, showing error " Expected { before if body ":
```
MAIN
    if()
```

But, when I ran the program:
```
MAIN
    if()
    {
    }
```
Then, again it showing the error which is showing in above case.

So, someone please help me to resolve this.

### CODE REVIEW

**Comment by Math-O5** [comment]
@jigyasudhingra That is weird. Maybe this is a bug from a wrong merge. My advice is keep your master branch clear to compare with your modified branch. 

Just discover, it may be a newline inserted by you or your editor, the error happens when there is no next line. 

To see, in function parser(), use this for debug:
```
for j in range(len(tokens)-1):
        print(tokens[j + 1].type)
```
The error still persist for 

```
MAIN
        var i = 3
        while() {
```
```
fun() {
```

The bug if with this statement, as you already note: 

```
# Check if ( follows id in function
    check_if(
        tokens[i + 1].type,

# Check if ( follows id in function
    check_if(
        tokens[i + 2].type,
```

Or any tokens[i + k]. You can do the check_incomplete function, but use it check_if too, that way we ensure check_if is a safe function.

**Comment by jigyasudhingra** [comment]
Yes, it is exactly what is happening whenever I try to run. It accounts newline as well into it because of which 'while' loop (which checks for newline) becomes infinite loop and it throws overflow error.

I don't think so, modifications in check_if works for every case because whenever while loop run to find left_brace, it always throw error, so, I have to put something before while loop to check whether tokens are present.

I tried this also, but the compiler take account the newline when runs.

**Comment by Math-O5** [comment]
@jigyasudhingra  I would suggest create a function is_equal(tokens, i, expected) which responsible by comparation that will compare tokens, if out of range throw a error. And do the same check in check_if. I suggest start with the new master, which update and splitted simc_parse in small pieces.

**Review by Math-O5 — CHANGES_REQUESTED** [review]
Forgot to add review, branch conflict

**Pull request closed without merging**
