### PR TITLE
fixed the issue 427

### PR DESCRIPTION
**Pull request by shobhit10058**
fixes issue #427.
The code -
```
MAIN
	var name[30] = {1,2,3}
END_MAIN
```
now gives no error

### CODE REVIEW

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
@shobhit10058 can you also add a short simc script that uses array declaration in simc-codes. Name it array-declaration.simc

**Review by Math-O5 — APPROVED** [review]

**Comment by shobhit10058** [comment]
in simc-codes folder only I guess?

**Comment by shobhit10058** [comment]
There was also a problem coming with 
print(name[0]) . There was some problem with expression function -> left and right brackets were not in OP_TOKENS. I have added them too.

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
But as far as I know array indexing isn't supported yet. This will compile as it will consider it an array declaration statement, but in the parsing there needs to be index out of bounds check if possible so I would suggest you to remove the print(name[0]) from your simc script.

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this. Closes #427.

**Pull request merged**
