### PR TITLE
Fixed #361  where check_if will always overflow.

### LINKED ISSUE #361: [BUG REPORT] Throwing simc overflow error to user
**Describe the bug**
When user type incomplete programs, the "check_if[i + 1]" will always overflow. 

The sintax is wrong, but the program should treat this properly. 

**To Reproduce**
Complie this simc code:

test.simc:

```
MAIN
    if()
```

```
MAIN
    var
```

```
MAIN
    f
```

```
MAIN
    array overflow
```

**Expected behavior**
A kind message error for user

**Desktop (please complete the following information):**
 - OS: Fedora 30, Ubuntu 18

### PR DESCRIPTION
**Pull request by lolzone13**
Fixes bug report #361.
Created a function check_incomplete in global_helpers that does a bounds check.
And used the function in the parser files wherever tokens[i+1] was used.
Displays "Code is incomplete" as an error message.

### CODE REVIEW

**Comment by Math-O5** [comment]
@frankhart2018 if check_incomplete was used inside check_if, it would be better? That way, when used check_if will be no need for call check_incomplete

**Comment by frankhart2018** [comment]
@Math-O5 agreed.

**Comment by lolzone13** [comment]
So, I'll just have to make modifications to check_if such that it does the bounds check and after that I can remove the check_incomplete function right?

**Comment by frankhart2018** [comment]
Yeah that would be better :)

**Comment by lolzone13** [comment]
But is the function I created okay? Or should I make changes to it as well?

**Pull request closed without merging**
