### PR TITLE
In-344 Add declaration of array

### LINKED ISSUE #344: [FEATURE] Array declaration (static array)
**Describe the solution you'd like**
Array declaration with or without assignment.

<strong>Syntax</strong>
Without assignment : 
var <array_name>[<size>]

<strong>Syntax</strong>
With assignment : 
array <array_name>[<size>] = {values separated by commas(,)}

### PR DESCRIPTION
**Pull request by Math-O5**
resolves #344 
 
Tested codes:

simc:
```
    var a = "a"
    var i = '4.0'
    array immm[30] = {"aaa", "bbbb"}
    //print(immm[0])
```
simc:
```
fun sum(i, j) {
     return i  + j
}

MAIN
    var i = 4
    array numbers[30] = {i, sum(i, i), 2}

END_MAIN
```
Output: c code

simc:
```
MAIN
    var i = 4
    array numbers[30] = {i, 1, 2}

END_MAIN
```
Output: c code

```
	int i = 4;
	int numbers[30] = {i, 1,2};
```

simc:
```
MAIN
    array numbers[30]
END_MAIN
```
Output: c code

`declared numbers[30];`

simc code:
```
MAIN
    var i = 'a'
    array numbers[30] = {a, 2}
END_MAIN
```
Output: Error, multiple types

### CODE REVIEW

**Comment by frankhart2018** [comment]
@Math-O5 did you add type checking for elements of array?

**Comment by Math-O5** [comment]
@frankhart2018 Yes, if type checking if ensure that if I start filling the array with integers, then swap to double, it'll throw an error.

**Comment by frankhart2018** [comment]
Cool, will go through the code and let you know. Also please check your LinkedIn 😄

**Review by frankhart2018 — CHANGES_REQUESTED** [review]
Hey @Math-O5, just one small change, we updated the syntax from array <arrayname> to var <arrayname> just to keep things consistent, otherwise code looks good.

**Comment by Math-O5** [comment]
@frankhart2018  As you wish:

fun kill_test() {
    return 3
}

sim-C code:
```
MAIN
    var bra[4] = {1,2,3}

    var sil[] = {1,2,3,4,5}

    var dont_use_kill_test[] = {kill_test(), kill_test()}

    var il = 4
    var l
END_MAIN
```
C code:

```
#include <stdio.h>

int kill_test(void) {

	return 3;
}

int main() {
	int bra[4] = {1,2,3};
	int sil[] = {1,2,3,4,5};
	int dont_use_kill_test[] = {kill_test(),kill_test()};
	int il = 4;
	declared l;

	return 0;
}
```

**Review by frankhart2018 — APPROVED** [review]
Looks good, merging this @Math-O5. Closes #344.

**Pull request merged**
